/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  OrderEnroll200,
  ReqAddOrderDto,
  SearchOrder200,
  SearchOrderParams
} from '../../dtos';

import { customInstance } from '../../../axios-client/customClient';
import type { ErrorType , BodyType } from '../../../axios-client/customClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 오더등록
 * @summary 오더등록
 */
export const orderEnroll = (
    reqAddOrderDto: BodyType<ReqAddOrderDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrderEnroll200>(
      {url: `/api/orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reqAddOrderDto, signal
    },
      options);
    }
  


export const getOrderEnrollMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof orderEnroll>>, TError,{data: BodyType<ReqAddOrderDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof orderEnroll>>, TError,{data: BodyType<ReqAddOrderDto>}, TContext> => {
    
const mutationKey = ['orderEnroll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof orderEnroll>>, {data: BodyType<ReqAddOrderDto>}> = (props) => {
          const {data} = props ?? {};

          return  orderEnroll(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrderEnrollMutationResult = NonNullable<Awaited<ReturnType<typeof orderEnroll>>>
    export type OrderEnrollMutationBody = BodyType<ReqAddOrderDto>
    export type OrderEnrollMutationError = ErrorType<unknown>

    /**
 * @summary 오더등록
 */
export const useOrderEnroll = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof orderEnroll>>, TError,{data: BodyType<ReqAddOrderDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof orderEnroll>>,
        TError,
        {data: BodyType<ReqAddOrderDto>},
        TContext
      > => {

      const mutationOptions = getOrderEnrollMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * 오더명검색
 * @summary 오더검색
 */
export const searchOrder = (
    params: SearchOrderParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SearchOrder200>(
      {url: `/api/orders/list`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getSearchOrderQueryKey = (params: SearchOrderParams,) => {
    return [`/api/orders/list`, ...(params ? [params]: [])] as const;
    }

    
export const getSearchOrderInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof searchOrder>>>, TError = ErrorType<unknown>>(params: SearchOrderParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchOrderQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchOrder>>> = ({ signal }) => searchOrder(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchOrderInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof searchOrder>>>
export type SearchOrderInfiniteQueryError = ErrorType<unknown>


export function useSearchOrderInfinite<TData = InfiniteData<Awaited<ReturnType<typeof searchOrder>>>, TError = ErrorType<unknown>>(
 params: SearchOrderParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchOrder>>,
          TError,
          Awaited<ReturnType<typeof searchOrder>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchOrderInfinite<TData = InfiniteData<Awaited<ReturnType<typeof searchOrder>>>, TError = ErrorType<unknown>>(
 params: SearchOrderParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchOrder>>,
          TError,
          Awaited<ReturnType<typeof searchOrder>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchOrderInfinite<TData = InfiniteData<Awaited<ReturnType<typeof searchOrder>>>, TError = ErrorType<unknown>>(
 params: SearchOrderParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 오더검색
 */

export function useSearchOrderInfinite<TData = InfiniteData<Awaited<ReturnType<typeof searchOrder>>>, TError = ErrorType<unknown>>(
 params: SearchOrderParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchOrderInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions , queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getSearchOrderQueryOptions = <TData = Awaited<ReturnType<typeof searchOrder>>, TError = ErrorType<unknown>>(params: SearchOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchOrderQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchOrder>>> = ({ signal }) => searchOrder(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchOrderQueryResult = NonNullable<Awaited<ReturnType<typeof searchOrder>>>
export type SearchOrderQueryError = ErrorType<unknown>


export function useSearchOrder<TData = Awaited<ReturnType<typeof searchOrder>>, TError = ErrorType<unknown>>(
 params: SearchOrderParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchOrder>>,
          TError,
          Awaited<ReturnType<typeof searchOrder>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchOrder<TData = Awaited<ReturnType<typeof searchOrder>>, TError = ErrorType<unknown>>(
 params: SearchOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchOrder>>,
          TError,
          Awaited<ReturnType<typeof searchOrder>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchOrder<TData = Awaited<ReturnType<typeof searchOrder>>, TError = ErrorType<unknown>>(
 params: SearchOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 오더검색
 */

export function useSearchOrder<TData = Awaited<ReturnType<typeof searchOrder>>, TError = ErrorType<unknown>>(
 params: SearchOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchOrder>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchOrderQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



