/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */
import type { ReqSearchPatientsDto } from './reqSearchPatientsDto';

export type GetAllPatientsByNameParams = {
dto: ReqSearchPatientsDto;
};
