/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */

export interface ReqAddVitalInAdmDto {
  /** 접수번호 */
  admId: number;
  /** 등록한 직원 코드 */
  usercode: string;
  /** 키 */
  height?: number;
  /** 몸무게 */
  weight?: number;
  /** 체온 */
  fever?: number;
}
