/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */

export interface ReqAddDiagnosisInAdmDto {
  /** 접수번호 */
  admId: number;
  /** 상병코드 */
  diseaseCode: string;
  /** 상병이름 */
  diseaseKName?: string;
}
