/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */

export interface ReqAddAdmissionDto {
  /** 환자차트번호 */
  patientId: string;
  /** 의사사번 */
  usercode: string;
  /** 진료과 */
  clinicDeft: string;
}
