/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 오더 등록
 */
export interface ReqAddOrderDto {
  /** 오더코드 */
  orderCode?: string;
  /** 오더명 */
  orderName?: string;
  /** 상대가치점수 */
  orderScore?: number;
}
