/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공지 수정
 */
export interface ReqModifyNoticeDto {
  title: string;
  content: string;
}
