/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */

export interface ReqPatientRegDto {
  /** 환자 이름 */
  patientName: string;
  /** 주민등록번호 */
  regidentNum: string;
  /** 휴대폰번호 */
  phoneNumber?: string;
}
