/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */

export interface ReqSignupDto {
  /** 성명 */
  username: string;
  /** 비밀번호 */
  password: string;
  /** 이메일 */
  email: string;
  /** 휴대폰 번호 */
  phoneNumber: string;
  /** 권한 ID */
  roleId: number;
}
