/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */

export interface ReqSigninDto {
  /** 사원번호 */
  usercode: string;
  /** 비밀번호 */
  password: string;
}
