/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공지사항 작성
 */
export interface ReqWriteNoticeDto {
  /** 제목 */
  title?: string;
  /** 내용 */
  content?: string;
}
