/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * carecheck
 * api 문서
 * OpenAPI spec version: 1.0.0
 */

export type SelectTotalByUserCodeAndYearParams = {
/**
 * 조회할 년도
 */
year: number;
/**
 * 조회할 사번
 */
usercode: string;
};
